config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "bookings#index"

  # bookings related routes
  get '/bookings', to: 'bookings#index'
  get '/bookings/new', to: 'bookings#new'
  get '/bookings/:id', to: 'bookings#show'
  get '/bookings/:id/edit', to: 'bookings#edit'
  post '/bookings', to: 'bookings#create'
  put '/bookings/:id', to: 'bookings#update'
  delete '/bookings/:id', to: 'bookings#destroy'

  # customers related routes
  get '/customers', to: 'customers#index'
  get '/customers/new', to: 'customers#new'
  get '/customers/:id', to: 'customers#show'
  get '/customers/:id/edit', to: 'customers#edit'
  post '/customers', to: 'customers#create'
  put '/customers/:id', to: 'customers#update'
  delete '/customers/:id', to: 'customers#destroy'

  get '/locations', to: 'locations#index'
  get '/pricings', to: 'durations#index'

  # get '/patients/:id', to: 'patients#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :bookings
end

app/models/duration.rb
class Duration < ApplicationRecord

end

app/models/location.rb
class Location < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find_by({id: params[:id]})
  end

  def new

  end

  def edit
    @booking = Booking.find_by({id: params[:id]})
  end

  def create
    @booking = Booking.create({
      location: params[:location],
      duration: params[:duration],
      price: params[:price],
      status: params[:status],
      customer_id: params[:customer_id]
    })
    redirect_to({controller: 'bookings', action: 'show', id: @booking.id })
  end

  def update
    @booking = Booking.find_by({id: params[:id]})
    @booking.update({
      location: params[:location],
      status: params[:status],
      price: params[:price],
      duration: params[:duration]
    })
    redirect_to({controller: 'bookings', action: 'show',id: @booking.id })
  end

  def destroy

  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
     @customer = Customer.find_by({id: params[:id]})
  end

  def new

  end

  def edit
    @customer = Customer.find_by({id: params[:id]})
  end

  def create
    Customer.create({ name: params[:name],email: params[:email],phone: params[:phone] })
    redirect_to({controller: 'customers', action: 'index' })
  end

  def update
    # find customer
    @customer = Customer.find_by({id: params[:id]})

    # update customer
    @customer.update({
      name: params[:name],
      email: params[:email],
      phone: params[:phone]
    })

    # redirect to customer's show page
    redirect_to({ controller: 'customers', action: 'show',id: @customer.id })
  end

  def destroy
    # find customer
    @customer = Customer.find_by({id: params[:id]})

    # destroy customer
    @customer.destroy

    # redirect to customer's index page
    redirect_to({ controller: 'customers', action: 'index' })
  end
end

app/controllers/durations_controller.rb
class DurationsController < ApplicationController

  def index
    @durations = Duration.all
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<br>
<h4 class="text-center">Edit Booking Details</h4>

<form action=<%= "/bookings/#{@booking.id}" %> method="put">
  <div class="form-group">
    <label for="location">Location:</label>
    <input type="text" id="location" class="form-control" placeholder="Enter location" name="location" value=<%= @booking.location %>  required>
    <br>
  </div>

  <div class="form-group">
    <label for="status">Status</label>
    <input type="text" id="status" class="form-control" placeholder="Enter status" name="status" value=<%= @booking.status %> required>
    <br>
  </div>

  <div class="form-group">
    <label for="duration">Duration</label>
    <input type="text" id="duration" class="form-control" placeholder="Enter duration" name="duration" value=<%= @booking.duration %> required>
    <br>
  </div>

  <div class="form-group">
    <label for="price">Price</label>
    <input type="text" id="price" class="form-control" placeholder="Enter price" name="price" value=<%= @booking.price %> required>
    <br>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/bookings/index.html.erb
<h1>Bookings</h1>

<div>
  <a href="/bookings/new">Add New Booking</a>
</div>

<div id="bookings">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Location</th>
        <th>Status</th>
        <th>Duration</th>
        <th>Price</th>
        <th>Customer Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.id %></td>
        <td><%= booking.location %></td>
        <td><%= booking.status %></td>
        <td><%= booking.duration %></td>
        <td><%= booking.price %></td>
        <td>
          <a href=<%= "/customers/#{booking.customer.id}" %>>
            <%= booking.customer.name %>
          </a>
        </td>
        <td colspan="3">
          <a href=<%= "/bookings/#{booking.id}" %>>Show</a>
          <a href=<%= "/bookings/#{booking.id}/edit" %>>Edit</a>
          <%= link_to "Destroy", bookings_path(booking), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/bookings/new.html.erb
<br>
<h4 class="text-center">New Booking Details</h4>

<form action="/bookings" method="post">
  <div class="form-group">
    <label for="location">Location:</label>
    <input type="text" id="location" class="form-control" placeholder="Enter location" name="location" required>
    <br>
  </div>

  <div class="form-group">
    <label for="status">Status</label>
    <input type="text" id="status" class="form-control" placeholder="Enter status" name="status" required>
    <br>
  </div>

  <div class="form-group">
    <label for="duration">Duration</label>
    <input type="text" id="duration" class="form-control" placeholder="Enter duration" name="duration" required>
    <br>
  </div>

  <div class="form-group">
    <label for="price">Price</label>
    <input type="text" id="price" class="form-control" placeholder="Enter price" name="price" required>
    <br>
  </div>

  <div class="form-group">
    <label for="customer_id">Customer Id</label>
    <input type="number" id="customer_id" class="form-control" placeholder="Enter Customer Id" name="customer_id" required>
    <br>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/bookings/show.html.erb
<div>
  <p>
    <strong>Booking location:</strong>
    <%= @booking.location %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @booking.status %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= @booking.duration %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @booking.price %>
  </p>

  <p>
    <a href=<%= "/bookings/#{@booking.id}/edit" %>>Edit</a>
    <li><%= link_to "Destroy", bookings_path(@booking), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  </p>
</div>

app/views/customers/edit.html.erb
<br>
<h4 class="text-center">Edit Customer Details</h4>

<form action=<%= "/customers/#{@customer.id}" %> method="put">
  <div class="form-group">
    <label for="name">Name:</label>
    <input type="text" id="name" class="form-control" placeholder="Enter name" name="name" value=<%= @customer.name %>  required>
    <br>
  </div>

  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" id="email" class="form-control" placeholder="Enter email" name="email" value=<%= @customer.email %> required>
    <br>
  </div>

  <div class="form-group">
    <label for="phone">Phone</label>
    <input type="tel" id="phone" class="form-control" placeholder="Enter phone" name="phone" pattern="[0-9]{10}" value=<%= @customer.phone %> required>
    <br>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/customers/index.html.erb
<h1>Customers</h1>

<div>
  <a href="/customers/new">Add New Customer</a>
</div>

<div id="customers">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.name %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td colspan="3">
          <a href=<%= "/customers/#{customer.id}" %>>Show</a>
          <a href=<%= "/customers/#{customer.id}/edit" %>>Edit</a>
          <%= link_to "Destroy", customers_path(customer), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/customers/new.html.erb
<br>
<h4 class="text-center">Enter New Customer Details</h4>

<form action="/customers" method="post">
  <div class="form-group">
    <label for="name">Name:</label>
    <input type="text" id="name" class="form-control" placeholder="Enter name" name="name" required>
    <br>
  </div>

  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" id="email" class="form-control" placeholder="Enter email" name="email" required>
    <br>
  </div>

  <div class="form-group">
    <label for="phone">Phone</label>
    <input type="tel" id="phone" class="form-control" placeholder="Enter phone" name="phone" pattern="[0-9]{10}" required>
    <br>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/customers/show.html.erb
<div>
  <p>
    <strong>Customer name:</strong>
    <%= @customer.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @customer.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @customer.phone %>
  </p>

  <p>
    <a href=<%= "/customers/#{@customer.id}/edit" %>>Edit</a>
    <li><%= link_to "Destroy", customers_path(@customer), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  </p>
</div>

app/views/durations/index.html.erb
<h1>Pricings</h1>

<div id="pricings">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Duration</th>
        <th>Price</th>
      </tr>
    </thead>

    <% @durations.each do |duration| %>
      <tr>
        <td><%= duration.time %></td>
        <td>$ <%= duration.price %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DroneService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand" href="/bookings">Drone Service</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class=<%= "nav-link" %> aria-current="page" href="/customers">
                Customers
              </a>
              <a class=<%= "nav-link" %> aria-current="page" href="/bookings">
                Bookings
              </a>
              <a class=<%= "nav-link" %> href="/locations">
                Locations
              </a>
              <a class=<%= "nav-link" %> href="/pricings">
                Pricing
              </a>
            </div>
        </div>
      </div>
    </nav>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Locations</h1>

<div id="locations">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>State</th>
      </tr>
    </thead>

    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.state %></td>
      </tr>
    <% end %>
  </table>
</div>